### PR TITLE
Add auto-author and auto-label to github workflow

### LINKED ISSUE #51: Implement auto-author-assign and auto-label workflows
The same as this issue in phys2bids (https://github.com/physiopy/phys2bids/issues/465) but implement for this repo

### PR DESCRIPTION
**Pull request by RayStick**
Closes #51 

## Proposed Changes

  - The same as [this PR for phys2bids](https://github.com/physiopy/phys2bids/pull/466) but implemented for this repo 
 - All I did was change the directory locations in the .github/labeler.yml file, otherwise the files are the same as the phys2bids files
 
## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [x] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [ ] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [ ] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [x] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [ ] My code respects the adopted style, especially linting conventions.
- [x] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [x] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [x] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Comment by RayStick** [comment]
@smoia ready to review but CircleCI not happy

**Comment by maestroque** [comment]
Does someone who has CircleCI access re-run the style_check pipeline? On #54 style_check can run normally (the repo gets ssh cloned normally)

We need to check if the current error is just random, because as it seems the circle ci configuration and keys to clone the phys2denoise repository are correct.

@RayStick @smoia

**Comment by RayStick** [comment]
thanks @maestroque  - I tried to re-run but these are the options I have (most are greyed out)
Screenshot 2024-07-12 at 15 13 42

**Comment by maestroque** [comment]
Same options for me, I think you need to have admin access in circleci to re-run. A new push should trigger a re-run though hopefully. 

Another thing that could have gone wrong would be that the workflow ssh keys are incorrect, however @smoia's recent pushes in master did manage to clone the repo with ssh in the pipeline, but the tests still failed due to outdated unit tests. These are fixed in #54 
@RayStick

**Comment by maestroque** [comment]
Now it seems that the errors are the same as in master branch

**Review by maestroque — APPROVED** [review]

**Comment by RayStick** [comment]
ok thanks @maestroque - should I merge for now?

**Comment by smoia** [comment]
OK this is not fun. You can merge despite issues cause your changes are not affecting or are affected by the CI failures.

The CI failures are related to numpy's versions and the numpy 2.0 release.

I do not know how to deal with this issue - the closest thing I saw is this PR: https://github.com/MIPLabCH/nigsp/pull/89

@msheltienne, could you help us with the numpy 2.0 incompatibility?

**Comment by maestroque** [comment]
@smoia could you open an issue to track this incompatibility?

**Pull request merged**
